#!/usr/bin/env bash

if [[ $# > 1  ]]; then
	echo "Too many arguments $@"
	exit 1
fi

if [[ $# < 1  ]]; then
	echo "Too few arguments $@"
	exit 1
fi
/usr/local/bin/pathsctools/checkpath $1
if [[ $? == 0 ]]; then
	lines=$(grep "alias $1=" $HOME/.path_aliases)
	tosearch="alias $1=\"cd \""
	lenlines=${#tosearch}
	temp=${lines:$lenlines}
	echo ${temp::(-2)}
	# echo ${lines}
else 
	exit 1
fi
exit 0
